markdown: kramdown
highlighter: pygments
permalink: /posts/:year/:month/:day/:title/
excerpt_separator: ""

repository: https://github.com/misol/misol.github.io

collections:
  docs:
    output: true

name: misol's blog
description: 한참 한참 만들어가는 misol의 블로그
url: https://misol.github.io
